{
    "port": 9001,

    "server_name": "potato annotator",

    "annotation_task_name": "Taxonomic methods",

    # Potato will write the annotation file for all annotations to this
    # directory, as well as per-annotator output files and state information
    # necessary to restart annotation.
    "output_annotation_dir": "annotation_output/",

    # The output format for the all-annotator data. Allowed formats are:
    # * jsonl
    # * json (same output as jsonl)
    # * csv
    # * tsv
    #
    "output_annotation_format": "tsv",

    # If annotators are using a codebook, this will be linked at the top to the
    # instance for easy access
    "annotation_codebook_url": "",

    "data_files": [
       "data_files/methods_text.json"
    ],

    "item_properties": {
        "id_key": "id",
        "text_key": "text"
    },

    "user_config": {
      "allow_all_users": True,
      "users": [ ],
    },

    "keyword_highlights_file": "frame_keywords.tsv",

    # How many seconds do you want the annotators spend on each instance, after
    # that, an alert will be sent per alert_time_each_instance seconds.
    "alert_time_each_instance": 10000000,
    "horizontal_key_bindings": true,

    "annotation_schemes": [
         {
            "annotation_type": "multiselect",
            "name": "high-level",
            "description": "high-level",
            "labels": [
               
                "PHENOTYPE",
                  "Phen_data",
                  "Phen_proc",
                 "Phen_analysis",
                "GENOTYPE",
                "Gen_data",
              "Gen_proc",
                "Gen_analysis",
               
            ]
        },
        {
            "annotation_type": "multiselect",
            "name": "Phen_data",
            "description": "Phen_datas",
            "labels": ["MORPH",
               
                "quant_morph",
                "qual_morph",
                  "color_pattern",
                  "shape",
                 "texture",
                "ultrastruct",
              "interbr_morph",
                "BEHAV",
                "acoustic",
                  "mating",
                  "feeding",
                 "ECOLOGY",  
                 
            ]
        },
        
        {
            "annotation_type": "multiselect",
            "name": "PhenProcAnal & GenProc",
            "description": "PhenProcAnal & GenProc",
            "labels": [
               "IMAGING",
                 "SAMPLING",
                "STORAGE",
                "phen_nonphylo",
                   "phen_pylo",
                   "SEQUENCING",
                  "gen1",
                   "gen2",
                  "gen3",
                  "genproc_other"
                
            ]
        },
        {
            "annotation_type": "multiselect",
            "name": "Gen_data & Gen_proc",
            "description": "Gen_data & Gen_proc",
            "labels": [
                "nuclear",
                  "organellar",
                 "transcriptomic",
                  "proteomic",
                   "tandem_repeats",
                  "whole_genomes",
                   "exomes",
                 "genome_wide",
                  "epigenetic",
                  "BIOCHEM",
                "chemotax",
                "cytotax",
                  "eDNA",
                  
            ]
        },

        {
            "annotation_type": "multiselect",
            "name": "Gen_analysis",
            "description": "Gen_analysis",
            "labels": ["GEN_NONPHYLO",
                "distance",
                  "haplowebs",
                  "fixed_alt_states",
                  "clustering",
                  "gen_interbr",
                  "PHYLO_SD",
                  "PHYLO_TREE", 
                  "distance_based",
                  "character_based",
                   "consensus_supertree",
                  "MACHINE_LEARNING",
            ]
        },
         {
            "annotation_type": "multiselect",
            "name": "Other",
            "description": "Other",
            "labels": [
               "specimen_storage_loc", "sampling_loc", "abbrev_terms", "nomenclat_history", "Interbreeding",
                "rank_just",
                "phylogenetic",
                "biogeo"
            ]
        }
    ],

    # The html that changes the visualiztation for your task. Change this file
    # to influence the layout and description of your task. This is not a full
    # HTML page, just the piece that does lays out your task's pieces
    "html_layout": "fixed_keybinding",


    # The core UI files for Potato. You should not need to change these normally.
    #
    # Exceptions to this might include:
    # 1) You want to add custom CSS/fonts to style your task
    # 2) Your layout requires additional JS/assets to render
    # 3) You want to support additional keybinding magic
    #
    # if you want to use your own template,
    # please replace the string as a path to the template
    "base_html_template": "default",
    "header_file": "default",

    # This is where the actual HTML files will be generated
    "site_dir": "default"


}
